/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package circuit_evaluator_package;

import java.util.ArrayList;

/**
 *
 * @author mtbjj
 */

public class circuitEvalframe extends javax.swing.JFrame {

    
    ArrayList<Node> nodes;
    Resistor r1;
    Resistor r2;
    Resistor r3;
    Resistor r4;
    VoltageSource battery;
    Circuit circuit = new Circuit();
    
    /**
     * Creates new form circuitEvalframe
     */
    
    public circuitEvalframe() {
        initComponents();
        r1 = new Resistor(3, "r1");
        r2 = new Resistor(2, "r2");
        r3 = new Resistor(1, "r3");
        r4 = new Resistor(7, "r4");
        battery = new VoltageSource(5, "b1");
        
//        /**Build the circuit from the defined elements*/
//        
//        //Connect R1 and R2 in series with battery
//        battery.terminal1.connect(r1.terminal1);
//        r1.terminal2.connect(r2.terminal1);
//        r1.terminal2.connect(battery.terminal2);
//        
//        //Connect R3 in series with R4
//        r3.terminal2.connect(r4.terminal2);
//        
//        //Connect R3 and R4 in parallel with R1 and R2
//        r3.terminal1.connect(r1.terminal2);
//        r4.terminal2.connect(r2.terminal2);
        
        /**Build the circuit from the defined elements*/
        circuit.addElement(r1);
        circuit.addElement(r2);
        circuit.addElement(r3);
        circuit.addElement(r4);
        circuit.addElement(battery);
/**       
* 
* 
* 
*                             R1                      R3
*                            3ohm                    1ohm
*                         /\  /\  /\             /\  /\  /\
*          -------------\/  \/  \/  \/----|----\/  \/  \/  \/-----|
*          |                              |                       |
*          |                              |                       |
*          |                              |                       |
*          |                              /                      /
*          |                             /                      /
*          |                             \                      \
*       +  |                              \                      \
*      _________   B                      /                      /
*        _____     1V                    /  R2                  /  R4
*          |                             \  2ohm                \  7ohm
*          |                              \                      \
*          |                              /                      /
*          |                             /                      /
*          |                             \                      \
*          |                              |                      |
*          |------------------------------|----------------------|
* 
* 
* 
* 
* 
*/                                        
        circuit.connectElements(battery.terminal1, r1.terminal1);
        circuit.connectElements(r1.terminal2, r2.terminal1);
        circuit.connectElements(r1.terminal2, r3.terminal1);
        circuit.connectElements(r3.terminal2, r4.terminal1);
        circuit.connectElements(r4.terminal2, battery.terminal2);
        circuit.connectElements(r2.terminal2, battery.terminal2);
        
        
        circuit.printNodes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(900, 600));
        setMinimumSize(new java.awt.Dimension(900, 600));
        setName("circuitEvalFrame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(900, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 946, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 563, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(circuitEvalframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(circuitEvalframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(circuitEvalframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(circuitEvalframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new circuitEvalframe().setVisible(true);
            }
        });
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
